### DISCUSSION TITLE
PHP binary not found at specified path: /usr/local/sbin/php. Please ensure PHP is installed.

### DISCUSSION THREAD

**Discussion by inpresif** [thedevdojo/wave#153] [Q&A] [answered]
Hi,

Never seen this issue before. Did a fresh install of Wave3 with Docker.
PHP is installed but not in sbin, just the regular /usr/local/bin/php.

Tried adding this in .env, no luck.
`PHP_BINARY=/usr/local/bin/php`

Is there any particular thing I need to change to be able to use this? Sorry I'm more of a vanilla PHP person, trying Wave for the First time. 

Thanks.

**Comment by bobbyiliev** [comment]
Hey @inpresif! 👋

Wave is indeed just a Laravel app, so it's mostly PHP under the hood.

That error usually happens when Laravel can't find the PHP binary at the expected path. As you are using Docker, can you share your Dockerfile here? It is possible that something in there might be missing.

Welcome to Wave! 🚀

\- Bobby

**Reply by inpresif** [reply]
Thanks Bobby,  My php Dockerfile is as follows:

```
# php/Dockerfile

# Use the official PHP image as the base
FROM php:8.3-fpm

# Set environment variables
ENV PHP_OPCACHE_ENABLE=0
ENV PHP_OPCACHE_ENABLE_CLI=0
ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
ENV PHP_OPCACHE_REVALIDATE_FREQ=0

# Install system dependencies
RUN apt-get update && apt-get install -y \
        libmagickwand-dev --no-install-recommends \
        build-essential \
        curl \
        ext-intl \
        ext-gd \
        gifsicle \
        git \
        jpegoptim \
        libbz2-dev \
        libcurl4-openssl-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libonig-dev \
        libpng-dev \
        libpq-dev \
        libxml2-dev \
        libzip-dev \
        locales \
        nginx \
        optipng \
        openssl \
        pngquant \
        unzip \
        vim \
        zip \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Install PHP extensions.
RUN docker-php-ext-install mysqli pdo pdo_mysql bcmath curl opcache mbstring zip exif pcntl 

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory
WORKDIR /var/www/html/

# Copy composer executable.
# COPY --from=composer:2.3.5 /usr/bin/composer /usr/bin/composer

# COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker/php/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf

COPY ./app/php/ /var/www/html/

# Expose port 80
EXPOSE 9000
```

My Docker-compose has this section for PHP:

```
php:
    container_name: php_dev
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app/php:/var/www/html
      - ./webdata/input/php:/var/www/html/webdata/input/php
      - ./webdata/output/php:/var/www/html/output/php
    depends_on:
      - mysql
      - redis
    ports: 
      - "9000:9000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
```
nginx config block

```
server {

    listen 80;

    server_name localhost 127.0.0.1 testsite.nl;

    root /var/www/html/public;
    index index.php index.htm index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Passes PHP requests to PHP-FPM container
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
    }
```

My other Laravel (vanilla) install works fine, calling regular index.php without Laravel also works when setting the root to /var/www/html/.

Thanks again.


EDIT:
Just put this exit() call on top of the Wave index.php file and it echoes the line just fine as well.
```
<?php
exit("hey buddy");
use Illuminate\Contracts\Http\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));
...
```
